### ISSUE TITLE
can't find label

### ISSUE THREAD

**Issue by haojingus** [GT-ZhangAcer/CaptchaDataset#2]
label_dict.txt   ？can't find it。

**Comment by GT-ZhangAcer** [comment]
Thank you for your attention. The label file is currently placed in the dataset directory. If it cannot be displayed normally, you can try to access the following link to get the test environment.
https://aistudio.baidu.com/aistudio/projectdetail/1147112
https://aistudio.baidu.com/aistudio/projectdetail/1100507

![Screenshot_2021-02-11-07-11-12-418_com android browser](https://user-images.githubusercontent.com/46156734/107584995-0a44ae00-6bc3-11eb-90db-49a68fa8876b.png)
