### ISSUE TITLE
请问有包含字母或者该数据集生成源码么？

### ISSUE THREAD

**Issue by Zhouxiaoqing** [GT-ZhangAcer/CaptchaDataset#3]
想生成或者收集一个类似形态但包含大小写字母的数据集。

**Comment by GT-ZhangAcer** [comment]
暂时没有，图像数据是网上找了个系统爬下来的，然后借助网上现有的免费OCR做初步识别。最后用模型训练一波，把异常梯度的label替换为模型推理的结果，数据集也就做出来了。
由于数据本身不复杂，所以就没有考虑更科学的方案。
关于自定义数据集生成源码，用pillow也可以自制一个，相信并不是很难



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月29日(周六) 凌晨0:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [GT-ZhangAcer/CaptchaDataset] 请问有包含字母或者该数据集生成源码么？ (#3)




 
想生成或者收集一个类似形态但包含大小写字母的数据集。
